import { test, expect } from '@playwright/test';
import { ProductPage } from '../pages/ProductPage';
import { CheckoutPage } from '../pages/CheckoutPage';
import { PaymentGatewayPage } from '../pages/PaymentGatewayPage';
import { OrderCompletedPage } from '../pages/OrderCompletedPage';

/**
 * Test spec — module Auto Voucher (TC_02.x), TC-MASTER-v1.2.xlsx.
 * Generated by /implement-automation on 2026-07-02.
 *
 * ⚠️ Naming: TC-MASTER dùng pattern `TC_02.X` (không phải `TC-<MODULE>-<NNN>` chuẩn) — giữ nguyên
 * theo quyết định ghi trong Source MEMORY §19 (traceability 1:1 với TC-MASTER = contract).
 *
 * Test data đã verify qua vibe-test (VR-003, VR-004):
 *   - Location A (5 EVC): Hà Nội / Phường Cầu Giấy / Phạm Văn Bạch
 *     → CA4699GIAM10KPHIHOAMANG (10.000đ, cao nhất), CA4431GIAMTTUFSA03 (5.000đ),
 *       CA4580GIAMTTUFSA03 (5.000đ), CA4608GIAMTTUFSA522 (0đ), CA4656GIAMUTFSANHHCM1 (0đ)
 *   - Location B (4 EVC — thiếu CA4656, ràng buộc HN/HCM): An Giang / Phường Châu Đốc / Kênh Hòa Bình
 *   - Location C (0 EVC): Hồ Chí Minh / Phường Test Hồ Chí Minh
 *   - Voucher PTTT=Momo only: CA4887GIAMTTUFSA03MOMO (5.000đ), chỉ xuất hiện khi PTTT=Ví MoMo
 *
 * Scope: 26 TC ✅ PASS (VR-003 + VR-004). KHÔNG bao gồm TC_02.12 (❌ FAIL — BUG-001 stacking,
 * xem review-src-tc / execute-maintain để thêm test regression riêng cho bug này).
 */

const LOCATION_A = { province: 'Hà Nội', ward: 'Phường Cầu Giấy', street: 'Phạm Văn Bạch' };
const LOCATION_B = { province: 'An Giang', ward: 'Phường Châu Đốc', street: 'Kênh Hòa Bình' };
const LOCATION_C = { province: 'Hồ Chí Minh', ward: 'Phường Test Hồ Chí Minh' };

/**
 * Helper: mở checkout mới + set địa chỉ Location A (deterministic 5-EVC context,
 * auto-apply CA4699). Dùng chung cho phần lớn TC — thay thế phụ thuộc vào IP-based
 * geo default (không ổn định giữa các môi trường/tester, xem vibe-locators-latest.md).
 */
async function setupCheckoutAtLocationA(page: import('@playwright/test').Page): Promise<CheckoutPage> {
  const productPage = new ProductPage(page);
  const checkoutPage = new CheckoutPage(page);

  await productPage.navigate();
  await productPage.clickMuaNgay();
  await checkoutPage.tickReceiveInvoice();
  await checkoutPage.selectAddress(LOCATION_A);

  return checkoutPage;
}

// ============================================================
// Group 1: Auto-apply & Context Switch
// TC_02.1, 2, 3, 4, 5, 13, 14, 15, 16
// ============================================================
test.describe('Auto-apply & Context Switch', () => {
  test('TC_02.1: Auto-apply voucher có DiscountVAT cao nhất khi lần đầu vào Thanh toán', async ({ page }) => {
    // Pre-condition: checkout có context đầy đủ, chưa có voucher, tài khoản có ≥2 EVC hợp lệ khác DiscountVAT
    const checkoutPage = await setupCheckoutAtLocationA(page);

    // Step 1-2: Truy cập URL màn Thanh toán, chờ tải xong, KHÔNG thao tác thêm
    // (setupCheckoutAtLocationA đã navigate + set context — chỉ còn quan sát)

    // Step 3: Quan sát block Voucher + dòng "Cần thanh toán"
    // Expected: CO tự áp đúng 1 EVC có DiscountVAT cao nhất (CA4699, 10.000đ — cao nhất trong 5 EVC)
    const codes = await checkoutPage.getAppliedVoucherCodes();
    expect(codes).toHaveLength(1);
    expect(codes[0]).toContain('CA4699GIAM10KPHIHOAMANG');

    // Expected: "Cần thanh toán" = giá gốc − discount = 39.900 − 10.000 = 29.900đ
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('29.900đ');
  });

  test('TC_02.2: Đổi context (chỉ voucher auto) → remove voucher cũ + apply best mới', async ({ page }) => {
    // Pre-condition: checkout đang có voucher V1 auto-apply; hasManualVoucher=false
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(1);

    // Step 1: Đổi địa chỉ sang context mới (Location B — vẫn có EVC hợp lệ)
    await checkoutPage.selectAddress(LOCATION_B);

    // Step 2-3: Chờ xử lý lại, quan sát block voucher + "Cần thanh toán"
    // Expected: CO remove V1, tìm voucher tốt nhất context mới, apply, tính lại — không crash/stuck
    // (verified VR-004: badge 5→4, CO tự gọi lại apply mode=Auto; best vẫn CA4699 vì cao nhất ở cả 2 context)
    await expect.poll(() => checkoutPage.getVoucherBadgeCount()).toBe(4);
    await expect.poll(() => checkoutPage.getAppliedVoucherCodes()).toEqual(
      expect.arrayContaining([expect.stringContaining('CA4699GIAM10KPHIHOAMANG')])
    );
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('29.900đ');
  });

  test('TC_02.3: Giữ voucher còn valid sau khi đổi context (hasManualVoucher=true)', async ({ page }) => {
    // Pre-condition: hasManualVoucher=true (voucher manual đang áp); voucher vẫn hợp lệ với context mới
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699 (auto)
    await checkoutPage.toggleVoucherInModal(1); // check CA4431 (manual)
    await checkoutPage.confirmVoucherModal();
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('34.900đ');

    // Step 1: Đổi context (PTTT → Ví MoMo) — voucher CA4431 (General, không ràng buộc PTTT) vẫn hợp lệ
    await checkoutPage.selectPaymentMethod('Ví MoMo');

    // Step 2-3: FE apply lại [auto+manual], quan sát voucher + giá
    // Expected: CO GetEvoucherInfor + Recheck; voucher giữ nguyên trong checkout; giá tính với voucher đó
    await expect.poll(() => checkoutPage.getAppliedVoucherCodes()).toEqual(
      expect.arrayContaining([expect.stringContaining('CA4431GIAMTTUFSA03')])
    );
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('34.900đ');
  });

  test('TC_02.4: User bỏ voucher manual → giữ voucher auto, cập nhật hasManualVoucher', async ({ page }) => {
    // Pre-condition: checkout có cả voucher manual và auto (do BUG-001 stacking — 2 voucher cùng active)
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(1); // thêm CA4431 (manual), KHÔNG bỏ CA4699 (auto)
    await checkoutPage.confirmVoucherModal();
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(2);

    // Step 1: Bỏ voucher manual (CA4431)
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(1); // uncheck CA4431
    await checkoutPage.confirmVoucherModal();

    // Step 2: Quan sát voucher còn lại + flag
    // Expected: CO chỉ remove voucher manual; voucher auto (CA4699) giữ nguyên
    const codes = await checkoutPage.getAppliedVoucherCodes();
    expect(codes).toHaveLength(1);
    expect(codes[0]).toContain('CA4699GIAM10KPHIHOAMANG');
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('29.900đ');
  });

  test('TC_02.5: Đổi context khi chỉ còn voucher manual → chỉ revalidate manual, không auto mới', async ({
    page,
  }) => {
    // Pre-condition: checkout chỉ còn voucher manual (auto đã bị bỏ); hasManualVoucher=true
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699 (auto)
    await checkoutPage.toggleVoucherInModal(1); // check CA4431 (manual)
    await checkoutPage.confirmVoucherModal();

    // Step 1: Đổi context → FE apply lại [manual]
    await checkoutPage.selectPaymentMethod('Ví MoMo');

    // Step 2: Quan sát voucher + có voucher auto mới không
    // Expected: CO GetEvoucherInfor + Recheck voucher manual; giữ nếu valid; KHÔNG apply voucher auto mới
    // (badge tăng 5→6 vì CA4887-Momo xuất hiện trong list, nhưng KHÔNG tự động được apply)
    await expect.poll(() => checkoutPage.getVoucherBadgeCount()).toBe(6);
    const codes = await checkoutPage.getAppliedVoucherCodes();
    expect(codes).toHaveLength(1);
    expect(codes[0]).toContain('CA4431GIAMTTUFSA03');
  });

  test('TC_02.13: hasManualVoucher=true → CO KHÔNG tự auto-apply khi đổi context', async ({ page }) => {
    // Pre-condition: checkout có ≥1 voucher manual + 1 auto (hasManualVoucher=true)
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699
    await checkoutPage.toggleVoucherInModal(1); // check CA4431 (manual)
    await checkoutPage.confirmVoucherModal();
    const priceBefore = await checkoutPage.getTotalPriceText();

    // Step 1: Đổi Gói/PTTT/địa chỉ
    await checkoutPage.selectPaymentMethod('Ví MoMo');

    // Step 2: Quan sát hành vi CO — không có voucher auto MỚI tự xuất hiện ngoài request FE
    // Expected: CO KHÔNG tự chạy auto-apply; giá giữ nguyên như trước khi đổi context
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe(priceBefore);
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(1);
  });

  test('TC_02.14: Không auto-apply voucher mới thay thế voucher bị remove', async ({ page }) => {
    // Pre-condition: voucher bị remove sau revalidate (hasManualVoucher=true)
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.selectPaymentMethod('Ví MoMo');
    await checkoutPage.openVoucherModal();
    const momoIndex = 3; // CA4887GIAMTTUFSA03MOMO — verify vị trí qua modal trước khi chạy thật
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699 (auto)
    await checkoutPage.toggleVoucherInModal(momoIndex); // check CA4887 (manual, Momo-only)
    await checkoutPage.confirmVoucherModal();
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('34.900đ');

    // Step 1: Tạo trạng thái voucher bị remove sau đổi context (đổi PTTT khỏi Momo → CA4887 invalid)
    await checkoutPage.selectPaymentMethod('Thẻ ATM');

    // Step 2-3: Chờ CO xử lý xong, quan sát có voucher mới tự thay thế không
    // Expected: CO KHÔNG tự tìm + apply voucher mới thay thế (dù CA4699 10.000đ khả dụng lại);
    // "Cần thanh toán" về giá gốc (không có voucher nào còn lại)
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(0);
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('39.900đ');
  });

  test('TC_02.15: User bỏ voucher auto → remove, KHÔNG auto-apply lại', async ({ page }) => {
    // Pre-condition: checkout có voucher auto, không có manual
    const checkoutPage = await setupCheckoutAtLocationA(page);

    // Step 1: Bấm bỏ/xóa voucher auto (uncheck trong modal, Xác nhận = FE gọi Apply rỗng)
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699
    await checkoutPage.confirmVoucherModal();

    // Step 2: Quan sát voucher + giá
    // Expected: CO remove voucher; dù hasManualVoucher=false, CO KHÔNG auto-apply lại; giá về giá gốc
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(0);
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('39.900đ');
  });

  test('TC_02.16: Sau khi user chủ động bỏ voucher + đổi context → KHÔNG auto-apply', async ({ page }) => {
    // Pre-condition: user vừa bỏ voucher; hasManualVoucher=false; còn EVC hợp lệ trong tài khoản
    const checkoutPage = await setupCheckoutAtLocationA(page);

    // Step 1: Bỏ voucher đang áp
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0);
    await checkoutPage.confirmVoucherModal();
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('39.900đ');

    // Step 2-3: Đổi Gói/PTTT/địa chỉ, chờ CO nhận context change
    await checkoutPage.selectPaymentMethod('Ví MoMo');

    // Step 4: Quan sát block voucher + giá
    // Expected: CO KHÔNG auto-apply (user đã chủ động bỏ = quyết định không dùng); giá giữ giá gốc
    // (badge vẫn tăng 5→6 do list refresh theo PTTT, nhưng KHÔNG tự apply)
    await expect.poll(() => checkoutPage.getVoucherBadgeCount()).toBe(6);
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('39.900đ');
  });
});

// ============================================================
// Group 2: Manual Selection & Popup Behavior
// TC_02.8, 9, 36
// ============================================================
test.describe('Manual Selection & Popup Behavior', () => {
  test("TC_02.8: Chọn EVC hợp lệ + 'Đồng ý' → cập nhật giá giảm và tổng đơn", async ({ page }) => {
    // Pre-condition: popup danh sách EVC đang mở; checkout chưa áp voucher
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699 auto trước, để test chọn thủ công sạch
    await checkoutPage.confirmVoucherModal();
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(0);

    // Step 1: Chọn 1 EVC hợp lệ (click checkbox)
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(1); // CA4431

    // Step 2-3: Bấm "Đồng ý" (Xác nhận), chờ loading
    await checkoutPage.confirmVoucherModal();

    // Step 4: Quan sát màn Thanh toán sau khi popup đóng
    // Expected: popup đóng; số tiền giảm hiển thị; "Cần thanh toán" = giá gốc − discount; EVC "đang áp dụng"
    await expect.poll(() => checkoutPage.getSuccessMessageText()).toContain('Áp dụng mã ưu đãi thành công.');
    const codes = await checkoutPage.getAppliedVoucherCodes();
    expect(codes[0]).toContain('CA4431GIAMTTUFSA03');
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('34.900đ');
  });

  test('TC_02.9: Hủy EVC đang áp (uncheck + Đồng ý) → reset giá gốc, không call QLCS', async ({ page }) => {
    // Pre-condition: đã apply 1 EVC; màn hiển thị giá đã giảm
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('29.900đ');

    // Step 1: Mở lại popup danh sách EVC
    await checkoutPage.openVoucherModal();

    // Step 2: Bỏ chọn EVC đang áp (uncheck)
    await checkoutPage.toggleVoucherInModal(0);

    // Step 3: Bấm "Đồng ý" xác nhận hủy
    await checkoutPage.confirmVoucherModal();

    // Step 4: Quan sát màn Thanh toán
    // Expected: "Cần thanh toán" = giá gốc (chính xác); số tiền giảm biến mất; EVC không còn "đang áp dụng"
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('39.900đ');
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(0);
  });

  test('TC_02.36: Đóng popup EVC (X) không thay đổi state checkout', async ({ page }) => {
    // Pre-condition: popup EVC mở; chưa thao tác chọn EVC trong lần này
    const checkoutPage = await setupCheckoutAtLocationA(page);
    const priceBefore = await checkoutPage.getTotalPriceText();
    await checkoutPage.openVoucherModal();

    // Step 1: Chọn 1 checkbox khác (thao tác trong modal, chưa confirm) rồi bấm X — KHÔNG confirm
    await checkoutPage.toggleVoucherInModal(2); // chọn thêm CA4580, chưa Xác nhận
    await checkoutPage.closeVoucherModal();

    // Step 2: Quan sát trạng thái màn Thanh toán
    // Expected: popup đóng; state checkout KHÔNG đổi (giá giữ nguyên như trước khi mở modal)
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe(priceBefore);
  });
});

// ============================================================
// Group 3: PTTT-specific Voucher & Recheck
// TC_02.11, 20, 21, 24, 6
// ============================================================
test.describe('PTTT-specific Voucher & Recheck', () => {
  test('TC_02.11: Lọc voucher theo điều kiện địa chỉ + PTTT + chu kỳ', async ({ page }) => {
    // Pre-condition: QLCS trả điều kiện theo địa chỉ/PTTT/chu kỳ; một số voucher không thỏa đơn
    const checkoutPage = await setupCheckoutAtLocationA(page);

    // Step 1: PTTT mặc định (Thẻ ATM) — CA4887 (Momo-only) KHÔNG xuất hiện
    await checkoutPage.openVoucherModal();
    await expect.poll(() => checkoutPage.getModalVoucherCount()).toBe(5);
    await checkoutPage.closeVoucherModal();

    // Step 2-3: Đổi PTTT = Momo, mở "Chọn ưu đãi", quan sát danh sách
    await checkoutPage.selectPaymentMethod('Ví MoMo');
    await checkoutPage.openVoucherModal();

    // Step 4-5: Đổi PTTT/địa chỉ/chu kỳ sang giá trị khác, quan sát danh sách cập nhật
    // Expected: danh sách CHỈ hiển thị voucher thỏa PTTT hiện tại; list cập nhật không chuyển màn
    await expect.poll(() => checkoutPage.getModalVoucherCount()).toBe(6); // +CA4887 Momo-only
  });

  test('TC_02.20: Remove voucher invalid sau đổi context + thông báo tiếng Việt', async ({ page }) => {
    // Pre-condition: hasManualVoucher=true; sau đổi context voucher X không còn hợp lệ
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.selectPaymentMethod('Ví MoMo');
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699
    await checkoutPage.toggleVoucherInModal(3); // check CA4887 (Momo-only)
    await checkoutPage.confirmVoucherModal();

    // Step 1: Đổi PTTT khiến voucher X (CA4887) invalid
    await checkoutPage.selectPaymentMethod('Thẻ ATM');

    // Step 2-3: Chờ xử lý xong, quan sát thông báo + khu vực voucher
    // Expected: CO remove X, tính lại; hiển thị thông báo tiếng Việt; mã X + discount biến mất; giá về giá gốc
    await expect.poll(() => checkoutPage.isInvalidVoucherMessageVisible()).toBe(true);
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(0);
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('39.900đ');
  });

  test('TC_02.21: Đổi context, voucher manual invalid → remove + thông báo', async ({ page }) => {
    // Pre-condition: chỉ còn voucher manual; voucher manual không hợp lệ context mới
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.selectPaymentMethod('Ví MoMo');
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699
    await checkoutPage.toggleVoucherInModal(3); // check CA4887 (manual, Momo-only)
    await checkoutPage.confirmVoucherModal();

    // Step 1: Đổi context khiến manual invalid (đổi PTTT khỏi Momo)
    await checkoutPage.selectPaymentMethod('Thẻ ATM');

    // Step 2-3: Chờ xử lý, quan sát voucher + thông báo + giá
    // Expected: CO nhận invalid, remove voucher manual, tính lại giá gốc, trả thông báo phù hợp
    await expect.poll(() => checkoutPage.isInvalidVoucherMessageVisible()).toBe(true);
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('39.900đ');
  });

  test('TC_02.24: Voucher đã áp không còn thỏa điều kiện (đổi PTTT) → tự xóa + reload list', async ({
    page,
  }) => {
    // Pre-condition: đã áp voucher V thỏa điều kiện hiện tại (PTTT=Momo)
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await checkoutPage.selectPaymentMethod('Ví MoMo');
    await checkoutPage.openVoucherModal();
    await checkoutPage.toggleVoucherInModal(0); // uncheck CA4699
    await checkoutPage.toggleVoucherInModal(3); // check CA4887 (Momo-only)
    await checkoutPage.confirmVoucherModal();
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('34.900đ');

    // Step 1: Đổi PTTT sang khác Momo (V không còn thỏa)
    await checkoutPage.selectPaymentMethod('Thẻ ATM');

    // Step 2: Quan sát voucher + giá + danh sách
    // Expected: hệ thống tự XÓA voucher V; tính lại "Cần thanh toán"; danh sách reload chỉ còn voucher thỏa
    // điều kiện mới (badge về 5); có thông báo voucher bị gỡ; không chuyển màn
    await expect.poll(() => checkoutPage.getAppliedVoucherCount()).toBe(0);
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('39.900đ');
    await expect.poll(() => checkoutPage.getVoucherBadgeCount()).toBe(5);
    await expect(page).toHaveURL(/\/checkout\/.+\/payment/); // không chuyển màn
  });

  test('TC_02.6: Recheck lúc Thanh toán hợp lệ (result=1) → tạo order thành công', async ({ page }) => {
    // Pre-condition: đã apply EVC hợp lệ; Recheck sẽ trả result=1
    const checkoutPage = await setupCheckoutAtLocationA(page);
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('29.900đ');

    // Điền thông tin cá nhân bắt buộc trước khi submit (không phải step trong TC — pre-condition ngầm)
    await checkoutPage.fillPersonalInfo({
      phone: '0912345678',
      name: 'Nguyen Van A',
      email: 'nguyenvana@test.com',
    });
    await checkoutPage.selectAddress({ ...LOCATION_A, houseNumber: '123' });
    await checkoutPage.selectPaymentMethod('Thẻ ATM');

    // Step 1: Bấm "Thanh toán"
    await checkoutPage.clickThanhToan();

    // Step 2: Chờ xử lý — redirect sang cổng thanh toán FoxPay/Napas
    const paymentGateway = new PaymentGatewayPage(page);
    await paymentGateway.fillCard({
      number: '9704000000000018', // Thẻ test STG (SaigonBank/Napas) — CHỈ dùng trên STG
      name: 'NGUYEN VAN A',
      expiry: '03/07',
    });
    await paymentGateway.clickPay();
    await paymentGateway.submitOtp('otp');

    // Expected: Recheck trả 1; điều hướng qua màn thanh toán thành công (đơn tạo với voucher đã áp)
    await expect.poll(() => paymentGateway.isSuccessVisible()).toBe(true);
    await paymentGateway.close();

    const orderCompletedPage = new OrderCompletedPage(page);
    await expect.poll(() => orderCompletedPage.isSuccessVisible()).toBe(true);
    const voucherCodes = await orderCompletedPage.getAppliedVoucherCodes();
    expect(voucherCodes[0]).toContain('CA4699GIAM10KPHIHOAMANG');
  });
});

// ============================================================
// Group 4: UI Display & Structure
// TC_02.10, 27, 28, 31, 33, 37, 38, 40
// ============================================================
test.describe('UI Display & Structure', () => {
  test('TC_02.10: Block CTKM hiển thị count EVC khả dụng khi load màn hình', async ({ page }) => {
    // Pre-condition: có ≥1 EVC hợp lệ với context checkout
    const checkoutPage = await setupCheckoutAtLocationA(page);

    // Step 1-2: Truy cập màn Thanh toán, chờ tải xong (không thao tác)
    // Step 3: Quan sát khu vực block CTKM/Ưu đãi
    // Expected: block tự hiển thị số EVC khả dụng (số nguyên > 0); không cần bấm thêm; không lỗi
    await expect.poll(() => checkoutPage.getVoucherBadgeCount()).toBe(5);
  });

  test("TC_02.27: Trang Cart hiển thị link nhập mã ưu đãi (default chưa áp voucher)", async ({ page }) => {
    // Ghi chú (VR-001 clarification từ BA): "Cart page" = trang Checkout hiện tại; textbox
    // "Nhập mã khuyến mãi" chính là link nhập mã ưu đãi trong TC gốc.
    const checkoutPage = await setupCheckoutAtLocationA(page);

    // Step 1-3: Truy cập trang Cart, quan sát Thông tin thanh toán, tìm phần nhập mã ưu đãi
    // Expected: textbox nhập mã ưu đãi hiển thị dưới dòng Tạm tính
    await expect.poll(() => checkoutPage.isPromoCodeInputVisible()).toBe(true);
  });

  test("TC_02.28: Trang Checkout hiển thị section 'Chọn ưu đãi'/'Áp dụng' (default chưa áp)", async ({
    page,
  }) => {
    // Pre-condition: KH ở Checkout đầy đủ; chưa áp voucher; đã điền PTTT
    const productPage = new ProductPage(page);
    const checkoutPage = new CheckoutPage(page);
    await productPage.navigate();
    await productPage.clickMuaNgay();
    // KHÔNG chọn địa chỉ ở đây — verify default state trước khi voucher context được set

    // Step 1-3: Truy cập Checkout, quan sát section Thông tin thanh toán, ghi nhận trạng thái voucher
    // Expected: button "Chọn ưu đãi" hiện; "Áp dụng" disabled/dạng link; không hiện voucher/discount
    // trước khi user tương tác (button Áp dụng luôn disabled — chỉ enable khi gõ mã tay)
    await expect.poll(() => checkoutPage.isVoucherTriggerVisible()).toBe(true);
    await expect.poll(() => checkoutPage.isApplyPromoEnabled()).toBe(false);
  });

  test('TC_02.31: Modal Empty State khi không có voucher khả dụng', async ({ page }) => {
    // Pre-condition: đơn không có voucher khả dụng (API trả list rỗng)
    const productPage = new ProductPage(page);
    const checkoutPage = new CheckoutPage(page);
    await productPage.navigate();
    await productPage.clickMuaNgay();
    await checkoutPage.tickReceiveInvoice();
    await checkoutPage.selectAddress(LOCATION_C); // 0 EVC

    // Step 1-2: Click "Chọn ưu đãi", chờ modal mở
    await checkoutPage.openVoucherModal();

    // Step 3: Quan sát nội dung modal
    // Expected: modal mở, hiện empty state; KHÔNG có nút "Xác nhận"
    await expect.poll(() => checkoutPage.isModalEmptyStateVisible()).toBe(true);
    await expect.poll(() => checkoutPage.getModalEmptyStateText()).toContain(
      'Rất tiếc, quý khách không có mã ưu đãi.'
    );
    await expect.poll(() => checkoutPage.isModalConfirmButtonVisible()).toBe(false);
  });

  test('TC_02.33: Mobile sticky bottom bar hiển thị voucher đã áp', async ({ page }) => {
    // Pre-condition: viewport mobile (≤768px); đã áp voucher V
    await page.setViewportSize({ width: 390, height: 844 });
    const checkoutPage = await setupCheckoutAtLocationA(page);

    // Step 1-2: Truy cập Checkout trên mobile, áp dụng voucher (đã auto-apply CA4699 sẵn)
    await expect.poll(() => checkoutPage.getTotalPriceText()).toBe('29.900đ');

    // Step 3: Quan sát sticky bottom bar dưới màn
    // Expected: sticky bar hiện; "Cần thanh toán" trong bar = giá đã giảm; nút "Tiếp tục" active
    await expect.poll(() => checkoutPage.isMobileStickyBarVisible()).toBe(true);
  });

  test('TC_02.37: Block CTKM ẩn/disabled khi không có EVC hợp lệ', async ({ page }) => {
    // Pre-condition: không có EVC hợp lệ với context
    const productPage = new ProductPage(page);
    const checkoutPage = new CheckoutPage(page);
    await productPage.navigate();
    await productPage.clickMuaNgay();
    await checkoutPage.tickReceiveInvoice();
    await checkoutPage.selectAddress(LOCATION_C); // 0 EVC

    // Step 1-2: Truy cập màn Thanh toán, chờ tải xong
    // Step 3: Quan sát khu vực block CTKM
    // Expected: badge ẩn (0/không hiện số); màn vẫn hoạt động bình thường, không lỗi
    await expect.poll(() => checkoutPage.getVoucherBadgeCount()).toBe(0);
    await expect.poll(() => checkoutPage.isVoucherTriggerVisible()).toBe(true); // trigger vẫn hiện, chỉ mất badge
  });

  test("TC_02.38: Badge số EVC khả dụng hiển thị đúng trên nút 'Chọn ưu đãi'", async ({ page }) => {
    // Pre-condition: có N EVC hợp lệ (N=5 tại Location A)
    const checkoutPage = await setupCheckoutAtLocationA(page);

    // Step 1-2: Quan sát nút "Chọn ưu đãi", ghi nhận số badge
    // Expected: badge hiển thị đúng số N (integer dương)
    const badgeCount = await checkoutPage.getVoucherBadgeCount();
    expect(badgeCount).toBe(5);
    expect(badgeCount).toBeGreaterThan(0);
  });

  test('TC_02.40: Popup EVC mở từ cache, không gọi lại GetListEvoucher', async ({ page }) => {
    // Pre-condition: đang ở Checkout; block CTKM count > 0
    const listRequests: string[] = [];
    page.on('request', (req) => {
      if (req.url().includes('/voucher/list')) listRequests.push(req.url());
    });

    const checkoutPage = await setupCheckoutAtLocationA(page);
    // Step 1: Xác nhận GetListEvoucher đã gọi khi load trang
    expect(listRequests.length).toBe(1);

    // Step 2: Bấm block CTKM/"Xem ưu đãi"
    await checkoutPage.openVoucherModal();

    // Step 3-4: Quan sát popup mở + Network tab, kiểm nội dung từng EVC row
    // Expected: popup mở ngay; Network KHÔNG có request GetListEvoucher mới (dùng cache)
    expect(listRequests.length).toBe(1);
    await expect.poll(() => checkoutPage.getModalVoucherCount()).toBe(5);
  });
});
