import { Page, Locator } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * CheckoutPage — màn hình Thanh toán (staging.fpt.vn/checkout/{orderId}/payment).
 * Bao gồm: Thông tin cá nhân, Địa chỉ lắp đặt, Phương thức thanh toán,
 * section Voucher (Thông tin thanh toán) + modal "Chọn ưu đãi".
 *
 * Generated by /implement-automation từ TC-MASTER-v1.2.xlsx (module Auto Voucher) on 2026-07-02.
 * Locator verified via Playwright MCP — 08_test-runs/vibe/VR-003-2026-07-02, VR-004-2026-07-02.
 *
 * Implements scenarios: TC_02.1-16, 20, 21, 24, 27, 28, 31, 33, 36-38, 40 (module Auto Voucher).
 */
export class CheckoutPage extends BasePage {
  // ===== Thông tin cá nhân =====
  private readonly phoneInput: Locator;
  private readonly nameInput: Locator;
  private readonly emailInput: Locator;
  private readonly receiveInvoiceCheckbox: Locator;

  // ===== Địa chỉ lắp đặt =====
  private readonly provinceButton: Locator;
  private readonly wardButton: Locator;
  private readonly streetButton: Locator;
  private readonly houseNumberInput: Locator;

  // ===== Phương thức thanh toán =====
  private readonly paymentMethodRadio: (name: string) => Locator;

  // ===== Section Voucher (Thông tin thanh toán) =====
  private readonly voucherTriggerLabel: Locator; // text "Chọn ưu đãi" (badge số là sibling element riêng, KHÔNG nối liền trong DOM thật)
  private readonly promoCodeInput: Locator;
  private readonly applyPromoButton: Locator;
  private readonly appliedVoucherCodes: Locator; // paragraph mã voucher đang áp (pattern CA****)
  private readonly totalPriceValue: Locator; // "Cần thanh toán" — giá trị cuối cùng, không có dấu "-"
  private readonly successMessage: Locator;
  private readonly invalidVoucherMessage: Locator;

  // ===== Modal "Chọn ưu đãi" =====
  private readonly modal: Locator;
  private readonly modalVoucherItem: Locator; // checkbox từng voucher (scoped trong modal)
  private readonly modalConfirmButton: Locator;
  private readonly modalCloseButton: Locator;
  private readonly modalEmptyStateImage: Locator;
  private readonly modalEmptyStateText: Locator;

  // ===== Thanh toán =====
  private readonly thanhToanButton: Locator;
  private readonly mobileStickyContinueButton: Locator; // CTA "Tiếp tục" trên sticky bottom bar (mobile ≤768px)

  constructor(page: Page) {
    super(page);

    this.phoneInput = page.getByRole('textbox', { name: 'Số điện thoại*' });
    this.nameInput = page.getByRole('textbox', { name: 'Họ tên*' });
    this.emailInput = page.getByRole('textbox', { name: 'Email*' });
    this.receiveInvoiceCheckbox = page.getByRole('checkbox', { name: /Tôi muốn nhận hóa đơn/ });

    this.provinceButton = page.getByRole('button', { name: 'Chọn tỉnh thành phố' });
    this.wardButton = page.getByRole('button', { name: 'Chọn phường/xã' });
    this.streetButton = page.getByRole('button', { name: 'Chọn tên đường' });
    this.houseNumberInput = page.getByRole('textbox', { name: 'Số nhà*' });

    this.paymentMethodRadio = (name: string) => page.getByRole('radio', { name });

    this.voucherTriggerLabel = page.getByText('Chọn ưu đãi', { exact: true });
    // Placeholder quan sát KHÔNG nhất quán giữa các lần chạy: "Nhập mã khuyến mãi" (VR-003/004)
    // vs "Nhập mã ưu đãi" (implement-automation run 2026-07-02) — dùng regex bao cả 2.
    this.promoCodeInput = page.getByRole('textbox', { name: /Nhập mã (khuyến mãi|ưu đãi)/ });
    this.applyPromoButton = page.getByRole('button', { name: 'Áp dụng' });
    // TODO: verify CSS tag thật (giả định <p>) khi có DOM thật — hiện dựa trên accessibility snapshot (role "paragraph")
    this.appliedVoucherCodes = page.locator('p').filter({ hasText: /^CA\d{3,}/ });
    this.totalPriceValue = page.locator('p').filter({ hasText: /^\d{1,3}(\.\d{3})*đ$/ }).last();
    this.successMessage = page.getByText(/Áp dụng (mã ưu đãi|ưu đãi mới) thành công\./);
    this.invalidVoucherMessage = page.getByText(
      'Ưu đãi đã chọn không đủ điều kiện áp dụng, vui lòng kiểm tra lại.'
    );

    this.modal = page.getByRole('dialog', { name: 'Chọn ưu đãi' });
    this.modalVoucherItem = this.modal.getByRole('checkbox');
    this.modalConfirmButton = this.modal.getByRole('button', { name: 'Xác nhận' });
    this.modalCloseButton = this.modal.getByRole('button', { name: 'Close' });
    this.modalEmptyStateImage = this.modal.getByRole('img', { name: 'Không có ưu đãi' });
    this.modalEmptyStateText = this.modal.getByText('Rất tiếc, quý khách không có mã ưu đãi.');

    this.thanhToanButton = page.getByRole('button', { name: 'Thanh toán', exact: true });
    this.mobileStickyContinueButton = page.getByRole('button', { name: 'Tiếp tục' });
  }

  // ===== Thông tin cá nhân =====

  /**
   * Điền thông tin cá nhân (SĐT bắt buộc; Họ tên/Email chỉ hiện sau khi tick "nhận hóa đơn").
   */
  async fillPersonalInfo(data: { phone?: string; name?: string; email?: string }): Promise<void> {
    if (data.phone) await this.phoneInput.fill(data.phone);
    if (data.name) await this.nameInput.fill(data.name);
    if (data.email) await this.emailInput.fill(data.email);
  }

  /**
   * Tick "Tôi muốn nhận hóa đơn" → mở form địa chỉ lắp đặt (Họ tên + Email hiện thêm).
   */
  async tickReceiveInvoice(): Promise<void> {
    await this.receiveInvoiceCheckbox.click();
  }

  // ===== Địa chỉ lắp đặt =====

  /**
   * Chọn địa chỉ lắp đặt (Tỉnh/Phường/Đường/Số nhà). Đây cũng là cách "đổi context"
   * để trigger CO re-evaluate voucher (TC_02.2, 3, 5, 13, 14, 16, 20, 21).
   */
  async selectAddress(data: {
    province: string;
    ward: string;
    street?: string;
    houseNumber?: string;
  }): Promise<void> {
    // Mỗi dropdown (Tỉnh/Phường/Đường) render dưới dạng role="dialog" riêng — scope + .last()
    // để tránh match nhầm dropdown cũ chưa kịp đóng (đã gặp trong thực tế khi chạy tự động).
    await this.provinceButton.click();
    await this.page.getByRole('dialog').last().getByText(data.province, { exact: true }).click();

    await this.wardButton.click();
    await this.page.getByRole('dialog').last().getByText(data.ward, { exact: true }).click();

    if (data.street) {
      await this.streetButton.click();
      await this.page.getByRole('dialog').last().getByText(data.street, { exact: true }).click();
    }
    if (data.houseNumber) await this.houseNumberInput.fill(data.houseNumber);

    // Đảm bảo dropdown cuối cùng đã đóng hẳn + context đã propagate (CO re-fetch voucher list)
    // trước khi tests tiếp tục đọc badge/giá — tránh flaky do đọc UI quá sớm.
    await this.page.keyboard.press('Escape');
    await this.page.waitForLoadState('networkidle');
  }

  // ===== Phương thức thanh toán =====

  /**
   * Chọn PTTT (Thẻ ATM / Ví MoMo / Thanh toán bằng VietQR / Chuyển khoản nhanh).
   * Đây cũng là cách "đổi context" phổ biến nhất để trigger CO re-evaluate voucher.
   */
  async selectPaymentMethod(name: string): Promise<void> {
    await this.paymentMethodRadio(name).click();
  }

  // ===== Voucher — section chính (Thông tin thanh toán) =====

  /**
   * Mở modal "Chọn ưu đãi".
   */
  async openVoucherModal(): Promise<void> {
    await this.voucherTriggerLabel.click();
    await this.waitForVisible(this.modal);
  }

  /**
   * Nhập mã khuyến mãi thủ công (textbox "Nhập mã khuyến mãi").
   */
  async enterPromoCode(code: string): Promise<void> {
    await this.promoCodeInput.fill(code);
  }

  async clickApplyPromo(): Promise<void> {
    await this.applyPromoButton.click();
  }

  async isApplyPromoEnabled(): Promise<boolean> {
    return this.applyPromoButton.isEnabled();
  }

  async isPromoCodeInputVisible(): Promise<boolean> {
    return this.promoCodeInput.isVisible();
  }

  /**
   * Lấy danh sách mã voucher đang áp dụng (0, 1, hoặc nhiều nếu bug stacking xảy ra).
   */
  async getAppliedVoucherCodes(): Promise<string[]> {
    return this.appliedVoucherCodes.allTextContents();
  }

  async getAppliedVoucherCount(): Promise<number> {
    return this.appliedVoucherCodes.count();
  }

  /**
   * Giá trị "Cần thanh toán" (text nguyên bản, vd "29.900đ").
   */
  async getTotalPriceText(): Promise<string> {
    return (await this.totalPriceValue.textContent())?.trim() ?? '';
  }

  /**
   * Badge số EVC khả dụng trên nút "Chọn ưu đãi" (0 nếu không có badge — 0 EVC).
   * Badge là 1 element riêng (sibling của label "Chọn ưu đãi" trong cùng container cha),
   * KHÔNG nối liền text label trong DOM thật.
   */
  async getVoucherBadgeCount(): Promise<number> {
    const container = this.voucherTriggerLabel.locator('xpath=..');
    const badge = container.getByText(/^\d+$/);
    if ((await badge.count()) === 0) return 0;
    const text = await badge.first().textContent();
    return text ? parseInt(text, 10) : 0;
  }

  async isVoucherTriggerVisible(): Promise<boolean> {
    return this.voucherTriggerLabel.isVisible();
  }

  async getSuccessMessageText(): Promise<string> {
    return (await this.successMessage.textContent())?.trim() ?? '';
  }

  async isInvalidVoucherMessageVisible(): Promise<boolean> {
    return this.invalidVoucherMessage.isVisible();
  }

  // ===== Modal "Chọn ưu đãi" =====

  async closeVoucherModal(): Promise<void> {
    await this.modalCloseButton.click();
  }

  async confirmVoucherModal(): Promise<void> {
    await this.modalConfirmButton.click();
  }

  /**
   * Chọn/bỏ chọn 1 voucher trong modal theo index (0-based, thứ tự hiển thị trong danh sách).
   */
  async toggleVoucherInModal(index: number): Promise<void> {
    await this.modalVoucherItem.nth(index).click();
  }

  async isVoucherCheckedInModal(index: number): Promise<boolean> {
    return this.modalVoucherItem.nth(index).isChecked();
  }

  /**
   * Số voucher hiển thị trong modal (dùng verify filter theo PTTT/địa chỉ — TC_02.11).
   */
  async getModalVoucherCount(): Promise<number> {
    return this.modalVoucherItem.count();
  }

  async isModalEmptyStateVisible(): Promise<boolean> {
    return this.modalEmptyStateImage.isVisible();
  }

  async getModalEmptyStateText(): Promise<string> {
    return (await this.modalEmptyStateText.textContent())?.trim() ?? '';
  }

  /**
   * TC_02.31: modal empty state KHÔNG có nút "Xác nhận".
   */
  async isModalConfirmButtonVisible(): Promise<boolean> {
    return this.modalConfirmButton.isVisible();
  }

  // ===== Thanh toán =====

  async clickThanhToan(): Promise<void> {
    await this.thanhToanButton.click();
  }

  /**
   * TC_02.33: sticky bottom bar chỉ hiện trên viewport mobile (≤768px) — chứa CTA "Tiếp tục".
   */
  async isMobileStickyBarVisible(): Promise<boolean> {
    return this.mobileStickyContinueButton.isVisible();
  }
}
