import { Page, Locator } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * OrderCompletedPage — màn "Hoàn tất đơn hàng" (staging.fpt.vn/checkout/{orderId}/completed).
 *
 * Generated by /implement-automation từ TC-MASTER-v1.2.xlsx (module Auto Voucher) on 2026-07-02.
 * Locator verified via Playwright MCP — 08_test-runs/vibe/VR-004-2026-07-02 (TC_02.6, order thật 0000JB8KK0CG).
 */
export class OrderCompletedPage extends BasePage {
  private readonly successHeading: Locator;
  private readonly orderCodeText: Locator;
  private readonly appliedVoucherCodes: Locator;

  constructor(page: Page) {
    super(page);
    this.successHeading = page.getByText('Thanh toán thành công');
    this.orderCodeText = page.getByText(/Mã đơn hàng: /);
    // TODO: verify CSS tag thật (giả định <p>) — hiện dựa trên accessibility snapshot (role "paragraph")
    this.appliedVoucherCodes = page.locator('p').filter({ hasText: /^CA\d{3,}/ });
  }

  async isSuccessVisible(): Promise<boolean> {
    return this.successHeading.isVisible();
  }

  async getOrderCode(): Promise<string> {
    const text = (await this.orderCodeText.textContent()) ?? '';
    return text.replace('Mã đơn hàng:', '').trim();
  }

  /**
   * Voucher đã áp vẫn hiển thị trong đơn hàng hoàn tất (verify Recheck result=1 giữ nguyên voucher).
   */
  async getAppliedVoucherCodes(): Promise<string[]> {
    return this.appliedVoucherCodes.allTextContents();
  }
}
