import { Page, Locator } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * PaymentGatewayPage — cổng thanh toán thẻ nội địa FoxPay/Napas
 * (portal-v2-staging.foxpay.vn/payment/domestic/card).
 *
 * Generated by /implement-automation từ TC-MASTER-v1.2.xlsx (module Auto Voucher) on 2026-07-02.
 * Locator verified via Playwright MCP — 08_test-runs/vibe/VR-004-2026-07-02 (TC_02.6, order thật đã tạo).
 *
 * Lưu ý: cổng thanh toán này là domain riêng (KHÔNG thuộc staging.fpt.vn), redirect từ
 * CheckoutPage.clickThanhToan() khi PTTT = Thẻ ATM.
 */
export class PaymentGatewayPage extends BasePage {
  private readonly cardNumberInput: Locator;
  private readonly cardNameInput: Locator;
  private readonly cardExpiryInput: Locator;
  private readonly payButton: Locator; // label động theo số tiền, vd "Thanh toán 29.900 VNĐ"
  private readonly otpInput: Locator;
  private readonly otpContinueButton: Locator;
  private readonly successText: Locator;
  private readonly closeButton: Locator;

  constructor(page: Page) {
    super(page);
    this.cardNumberInput = page.getByRole('textbox', { name: 'Số thẻ' });
    this.cardNameInput = page.getByRole('textbox', { name: 'Tên in trên thẻ' });
    this.cardExpiryInput = page.getByRole('textbox', { name: 'Ngày hiệu lực thẻ' });
    this.payButton = page.getByRole('button', { name: /Thanh toán .* VNĐ/ });
    this.otpInput = page.getByRole('textbox', { name: 'Mã xác thực (OTP)' });
    this.otpContinueButton = page.getByRole('button', { name: 'Tiếp tục' });
    this.successText = page.getByText('Giao dịch thành công.');
    this.closeButton = page.getByRole('button', { name: 'Đóng' });
  }

  /**
   * Điền thông tin thẻ test nội địa Napas. Ngân hàng tự động detect khi đủ số thẻ (vd SaigonBank).
   */
  async fillCard(data: { number: string; name: string; expiry: string }): Promise<void> {
    await this.cardNumberInput.fill(data.number);
    await this.cardNameInput.fill(data.name);
    await this.cardExpiryInput.fill(data.expiry);
  }

  async clickPay(): Promise<void> {
    await this.payButton.click();
  }

  /**
   * Nhập OTP (dialog Napas) + bấm "Tiếp tục".
   */
  async submitOtp(otp: string): Promise<void> {
    await this.otpInput.fill(otp);
    await this.otpContinueButton.click();
  }

  async isSuccessVisible(): Promise<boolean> {
    return this.successText.isVisible();
  }

  /**
   * Đóng dialog kết quả → redirect về CheckoutPage/OrderCompletedPage.
   */
  async close(): Promise<void> {
    await this.closeButton.click();
  }
}
