import { Page, Locator } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * ProductPage — trang sản phẩm Gói Ultra Fast (tongdaiwifi.vn).
 * Generated by /implement-automation từ TC-MASTER-v1.2.xlsx (module Auto Voucher) on 2026-07-02.
 * Locator verified via Playwright MCP — 08_test-runs/vibe/VR-003-2026-07-02, VR-004-2026-07-02.
 */
export class ProductPage extends BasePage {
  private readonly muaNgayButton: Locator;

  constructor(page: Page) {
    super(page);
    this.muaNgayButton = page.getByRole('button', { name: 'Mua ngay' });
  }

  /**
   * Truy cập trang sản phẩm Gói Ultra Fast. Tự động dismiss cookie consent banner
   * (chỉ xuất hiện trên browser context mới — xem BasePage.dismissCookieBanner).
   */
  async navigate(): Promise<void> {
    await this.goto('https://staging.tongdaiwifi.vn/dich-vu-so/goi-ultra-fast');
    await this.dismissCookieBanner();
  }

  /**
   * Click "Mua ngay" → redirect sang màn hình Thanh toán (CheckoutPage).
   */
  async clickMuaNgay(): Promise<void> {
    await this.muaNgayButton.click();
  }
}
